apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientes-app
  template:
    metadata:
      labels:
        app: clientes-app
    spec:
      containers:
      - name: clientes-app
        image: clientes-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
